
###

POST http://localhost:5000/api/v1/auth/register
Content-Type: application/json

{
    "email": "test1@test.com",
    "password": "1234567890"
}

###

POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
    "email": "test1@test.com",
    "password": "1234567890"
}

GET http://localhost:5000/api/v1/check
Content-Type: application/json

{
    "email": "test1@test.com",
    "password": "1234567890"
}